lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # clé de création du token
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # clé de validation du token
    pass_phrase: 'admin' # clé de la signature du token
    token_ttl: 20 # durée de validation
