security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\User: #plaintext
            algorithm: argon2i

    role_hierarchy:
        ROLE_MEMBER: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_MEMBER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        # indique quel entité on utilise pour l'authentification et le champ qui sert d'identifiant
        main:
            entity:
                class: App\Entity\User
                property: username
        
    firewalls:
        # gestion d'authentification en fonction des url
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: main
            guard:
                authenticators:
                    - App\Security\LoginAuthenticator
            logout:
                path: users_logout

    access_control:
        - { path: ^/events, roles: ROLE_MEMBER }
        - { path: ^/users, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
