lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' # clé de création du token (.env)
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'  # clé de validation du token (.env)
    pass_phrase: '%env(JWT_PASSPHRASE)%' # clé de la signature du token (.env)
    token_ttl: 3600 # durée de validation
    # token_ttl: 1209600 # durée de validation
